on:
  pull_request:
    branches:
      - main
    types: [closed]


jobs:
  check-coverage:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage --coverageThreshold='{"global":{"lines":50}}'

  build-and-push-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: check-coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            brightonkbgrow/cit262-brightonkbgrow-bb:latest
            brightonkbgrow/cit262-brightonkbgrow-bb:1.0
